import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const ROOT_DIR = path.dirname(fileURLToPath(import.meta.url));
const SRC_DIR = path.join(ROOT_DIR, 'tampermonkey-userscript-src');
const ENTRY_FILE = path.join(SRC_DIR, 'core', 'main.js');
const DIST_DIR = path.join(ROOT_DIR, 'dist');
const OUT_FILE = path.join(DIST_DIR, 'client.user.js');
const REPO_ROOT_CLIENT = path.join(ROOT_DIR, '..', 'client.user.js');
const ORDER_FILE = path.join(SRC_DIR, '.build-order.json');
const MOJIBAKE_MARKERS = [
  '鑷',
  '涓',
  '妯',
  '鐢?',
  '绛',
  '锛',
  '閿',
  '鏂',
  '鍒',
  '褰',
  '淇',
  '缁',
];

function loadBuildConfig() {
  if (!fs.existsSync(ORDER_FILE)) {
    throw new Error('.build-order.json not found at ' + ORDER_FILE);
  }
  return JSON.parse(fs.readFileSync(ORDER_FILE, 'utf8'));
}

function pad2(n) {
  return String(n).padStart(2, '0');
}

function buildGeneratedNotice() {
  const now = new Date();
  const buildTime = [
    now.getFullYear(),
    pad2(now.getMonth() + 1),
    pad2(now.getDate()),
  ].join('-') + ' ' + pad2(now.getHours()) + ':' + pad2(now.getMinutes()) + ':' + pad2(now.getSeconds());

  return [
    '// =============================================================================',
    '// GENERATED FILE - DO NOT EDIT DIRECTLY',
    '// =============================================================================',
    '// This file is generated by:',
    '// chatgpt-toolbox/build.userjs.mjs',
    '//',
    '// Source files are in:',
    '// chatgpt-toolbox/tampermonkey-userscript-src/',
    '//',
    '// To modify behavior, edit source files first, then run:',
    '// npm run build',
    '//',
    '// Generated JS body is ASCII-escaped to avoid Windows/clipboard encoding damage.',
    '//',
    '// Generated at: ' + buildTime,
    '// =============================================================================',
  ].join('\n');
}

function extractHeader(mainText) {
  const match = mainText.match(/^\/\/ ==UserScript==[\s\S]*?\/\/ ==\/UserScript==\r?\n/);
  if (!match) {
    throw new Error('Userscript header not found in ' + ENTRY_FILE);
  }
  return {
    header: match[0].trimEnd(),
    body: mainText.slice(match[0].length),
  };
}

function readUtf8File(filePath) {
  return fs.readFileSync(filePath, 'utf8');
}

function readPart(name) {
  const filePath = path.join(SRC_DIR, name);
  if (!fs.existsSync(filePath)) {
    throw new Error('Missing source part: ' + filePath);
  }
  return readUtf8File(filePath);
}

function findMojibakeMarkers(text) {
  const hits = [];
  for (const marker of MOJIBAKE_MARKERS) {
    if (text.includes(marker)) {
      hits.push(marker);
    }
  }
  return hits;
}

function assertNoMojibake(text, label) {
  const hits = findMojibakeMarkers(text);
  if (hits.length > 0) {
    throw new Error(
      [
        '[BUILD_ENCODING][MOJIBAKE_DETECTED]',
        'label=' + label,
        'markers=' + hits.join(','),
        'reason=source-or-output-looks-like-utf8-decoded-as-gbk',
      ].join(' '),
    );
  }
}

function escapeNonAsciiForJsSource(text) {
  let output = '';

  for (const char of text) {
    const codePoint = char.codePointAt(0);

    if (
      codePoint === 0x09
      || codePoint === 0x0a
      || codePoint === 0x0d
      || (codePoint >= 0x20 && codePoint <= 0x7e)
    ) {
      output += char;
      continue;
    }

    if (codePoint <= 0xffff) {
      output += '\\u' + codePoint.toString(16).padStart(4, '0');
    } else {
      output += '\\u{' + codePoint.toString(16) + '}';
    }
  }

  return output;
}

function assembleUserscript() {
  const config = loadBuildConfig();
  const allParts = config.parts || [];
  const marker = config.uploadInsertMarker || '/*__UPLOAD_MODULES__*/';

  if (!allParts.length) {
    throw new Error('.build-order.json is missing "parts" array');
  }

  const mainText = readUtf8File(ENTRY_FILE);
  assertNoMojibake(mainText, 'core/main.js');

  const { header, body: mainBody } = extractHeader(mainText);

  if (!mainBody.includes(marker)) {
    throw new Error(
      'core/main.js is missing upload insert marker ' + marker + '. '
      + 'Check that the upload module part has a matching InsertModule block.',
    );
  }

  const bodyParts = allParts.map((partName) => {
    if (partName === 'core/main.js') {
      return mainBody.replace(marker, '\n');
    }

    const partText = readPart(partName);
    assertNoMojibake(partText, partName);
    return partText;
  });

  const body = bodyParts.join('');
  assertNoMojibake(body, 'assembled-source-body');

  const bundled = '(function () {\n  \'use strict\';\n\n' + body + '})();';
  const bundledSanitized = bundled.replace(/\uFEFF/g, '');

  const asciiBundled = escapeNonAsciiForJsSource(bundledSanitized);

  return [header, buildGeneratedNotice(), asciiBundled, ''].join('\n\n');
}

function checkJavaScriptSyntax(filePath) {
  const result = spawnSync(process.execPath, ['--check', filePath], {
    encoding: 'utf8',
  });

  if (result.status !== 0) {
    const output = [
      result.stdout || '',
      result.stderr || '',
    ].join('\n').trim();

    throw new Error(
      'Generated userscript syntax check failed: ' + filePath + '\n' + output,
    );
  }
}

function writeOutput() {
  fs.mkdirSync(DIST_DIR, { recursive: true });

  const output = assembleUserscript();
  assertNoMojibake(output, 'generated-userscript');

  fs.writeFileSync(OUT_FILE, output, 'utf8');
  fs.writeFileSync(REPO_ROOT_CLIENT, output, 'utf8');

  checkJavaScriptSyntax(OUT_FILE);
  checkJavaScriptSyntax(REPO_ROOT_CLIENT);

  console.log('[BUILD][OK] Wrote ' + OUT_FILE);
  console.log('[BUILD][OK] Synced ' + REPO_ROOT_CLIENT);
  console.log('[BUILD][OK] JS body escaped to ASCII-safe unicode literals');
}

function watch() {
  writeOutput();

  console.log('Watching ' + SRC_DIR + ' ...');

  fs.watch(SRC_DIR, { recursive: true }, () => {
    try {
      writeOutput();
    } catch (err) {
      const message = err && err.stack ? err.stack : String(err);
      console.error('[BUILD][FAILED]\n' + message);
    }
  });
}

if (process.argv.includes('--watch')) {
  watch();
} else {
  writeOutput();
}
