import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const ROOT_DIR = path.dirname(fileURLToPath(import.meta.url));
const SRC_DIR = path.join(ROOT_DIR, 'tampermonkey-userscript-src');
const ENTRY_FILE = path.join(SRC_DIR, 'core', 'main.js');
const DIST_DIR = path.join(ROOT_DIR, 'dist');
const OUT_FILE = path.join(DIST_DIR, 'client.user.js');
const REPO_ROOT_CLIENT = path.join(ROOT_DIR, '..', 'client.user.js');
const ORDER_FILE = path.join(SRC_DIR, '.build-order.json');
const MOJIBAKE_MARKERS = [
  '鑷',
  '涓',
  '妯',
  '鐢?',
  '绛',
  '锛',
  '閿',
  '鏂',
  '鍒',
  '褰',
  '淇',
  '缁',
];

const OUTPUT_POLLUTION_MARKERS = [
  '\uFFFD',
  '锟斤拷',
  'ï¿½',
  '[QUESTION_PLACEHOLDER]',
];

const BAD_QUESTION_MARK_RE = /\?{3,}/;

function loadBuildConfig() {
  if (!fs.existsSync(ORDER_FILE)) {
    throw new Error('.build-order.json not found at ' + ORDER_FILE);
  }
  return JSON.parse(fs.readFileSync(ORDER_FILE, 'utf8'));
}

function pad2(n) {
  return String(n).padStart(2, '0');
}

function getBuildTimeString(now = new Date()) {
  return [
    now.getFullYear(),
    pad2(now.getMonth() + 1),
    pad2(now.getDate()),
  ].join('-') + ' ' + pad2(now.getHours()) + ':' + pad2(now.getMinutes()) + ':' + pad2(now.getSeconds());
}

function buildGeneratedNotice(buildTime) {
  const safeBuildTime = String(buildTime || '').trim() || 'unknown';

  return [
    '// =============================================================================',
    '// GENERATED FILE - DO NOT EDIT DIRECTLY',
    '// =============================================================================',
    '// This file is generated by:',
    '// chatgpt-toolbox/build.userjs.mjs',
    '//',
    '// Source files are in:',
    '// chatgpt-toolbox/tampermonkey-userscript-src/',
    '//',
    '// To modify behavior, edit source files first, then run:',
    '// npm run build',
    '//',
    '// Generated JS body is ASCII-escaped to avoid Windows/clipboard encoding damage.',
    '//',
    '// Generated at: ' + safeBuildTime,
    '// =============================================================================',
  ].join('\n');
}

function extractHeader(mainText) {
  const rawText = String(mainText || '').replace(/^\uFEFF/, '');
  const headerStart = rawText.indexOf('// ==UserScript==');
  if (headerStart < 0) {
    throw new Error('Userscript header not found in ' + ENTRY_FILE);
  }
  const leadingText = rawText.slice(0, headerStart);
  if (leadingText.trim()) {
    throw new Error(
      'Unexpected non-whitespace content before userscript header in ' + ENTRY_FILE,
    );
  }
  if (headerStart > 0) {
    console.warn(
      '[BUILD][HEADER_LEADING_WHITESPACE] '
      + 'Userscript header has leading whitespace; build will ignore it. '
      + 'file=' + ENTRY_FILE
      + ' leadingLength=' + headerStart,
    );
  }
  const textFromHeader = rawText.slice(headerStart);
  const match = textFromHeader.match(
    /^\/\/ ==UserScript==[\s\S]*?\/\/ ==\/UserScript==\n/,
  );
  if (!match) {
    throw new Error('Userscript header block is incomplete in ' + ENTRY_FILE);
  }
  return {
    header: match[0].trimEnd(),
    body: textFromHeader.slice(match[0].length),
  };
}

function normalizeBuildLineEndings(content, filePath) {
  const rawText = String(content || '').replace(/^\uFEFF/, '');
  const crcrlfCount = (rawText.match(/\r\r\n/g) || []).length;
  if (crcrlfCount > 0) {
    console.warn(
      '[BUILD][LINE_ENDING_NORMALIZED] '
      + `file=${filePath} pattern=CRCRLF count=${crcrlfCount}`,
    );
  }
  return rawText
    .replace(/\r\r\n/g, '\n')
    .replace(/\r\n/g, '\n')
    .replace(/\r/g, '\n');
}

function readUtf8File(filePath) {
  const content = normalizeBuildLineEndings(
    fs.readFileSync(filePath, 'utf8'),
    filePath,
  );
  assertNoBadControlChars(content, filePath);
  return content;
}

function readPart(name) {
  const filePath = path.join(SRC_DIR, name);
  if (!fs.existsSync(filePath)) {
    throw new Error('Missing source part: ' + filePath);
  }
  return readUtf8File(filePath);
}

function findFirstBadControlChar(text) {
  let line = 1;
  let column = 0;

  for (let i = 0; i < text.length; i += 1) {
    const char = text[i];

    if (char === '\n') {
      line += 1;
      column = 0;
      continue;
    }

    column += 1;

    const codePoint = char.codePointAt(0);
    const isAllowedWhitespace = codePoint === 0x09 || codePoint === 0x0d;

    if (isAllowedWhitespace) continue;

    if (codePoint < 0x20 || codePoint === 0x7f) {
      return {
        line,
        column,
        char,
        charCode: codePoint,
      };
    }
  }

  return null;
}

function snippetAt(text, idx, radius = 30) {
  const start = Math.max(0, idx - radius);
  const end = Math.min(text.length, idx + radius);
  return text.slice(start, end);
}

function assertNoBadControlChars(text, filePath) {
  if (text.startsWith('\uFEFF')) {
    throw new Error(
      [
        '[ENCODING][BAD_CHAR]',
        'file=' + filePath,
        'line=1',
        'column=1',
        'char_code=0xfeff',
        'snippet=' + JSON.stringify(snippetAt(text, 0)),
      ].join(' '),
    );
  }

  const bad = findFirstBadControlChar(text);
  if (!bad) return;

  const idx = text.indexOf(bad.char);
  const snippet = snippetAt(text, idx);

  throw new Error(
    [
      '[ENCODING][BAD_CHAR]',
      'file=' + filePath,
      'line=' + bad.line,
      'column=' + bad.column,
      'char_code=0x' + bad.charCode.toString(16),
      'snippet=' + JSON.stringify(snippet),
    ].join(' '),
  );
}

function findMojibakeMarkers(text) {
  const hits = [];
  for (const marker of MOJIBAKE_MARKERS) {
    if (text.includes(marker)) {
      hits.push(marker);
    }
  }
  return hits;
}

function assertNoMojibake(text, label) {
  const hits = findMojibakeMarkers(text);
  if (hits.length > 0) {
    throw new Error(
      [
        '[BUILD_ENCODING][MOJIBAKE_DETECTED]',
        'label=' + label,
        'markers=' + hits.join(','),
        'reason=source-or-output-looks-like-utf8-decoded-as-gbk',
      ].join(' '),
    );
  }
}

function toLineColumn(text, index) {
  let line = 1;
  let column = 1;

  for (let i = 0; i < index && i < text.length; i += 1) {
    if (text[i] === '\n') {
      line += 1;
      column = 1;
    } else {
      column += 1;
    }
  }

  return { line, column };
}

function scanJsStringLiterals(text, onHit) {
  let i = 0;
  let inLineComment = false;
  let inBlockComment = false;

  function isEscaped(pos) {
    let backslashes = 0;
    for (let k = pos - 1; k >= 0 && text[k] === '\\'; k -= 1) backslashes += 1;
    return backslashes % 2 === 1;
  }

  while (i < text.length) {
    const ch = text[i];
    const next = text[i + 1];

    if (inLineComment) {
      if (ch === '\n') inLineComment = false;
      i += 1;
      continue;
    }

    if (inBlockComment) {
      if (ch === '*' && next === '/') {
        inBlockComment = false;
        i += 2;
        continue;
      }
      i += 1;
      continue;
    }

    if (ch === '/' && next === '/') {
      inLineComment = true;
      i += 2;
      continue;
    }

    if (ch === '/' && next === '*') {
      inBlockComment = true;
      i += 2;
      continue;
    }

    if (ch === '\'' || ch === '"') {
      const quote = ch;
      const start = i;
      i += 1;
      let value = '';
      while (i < text.length) {
        const c = text[i];
        if (c === quote && !isEscaped(i)) break;
        value += c;
        i += 1;
      }
      onHit({ start, value });
      i += 1;
      continue;
    }

    if (ch === '`') {
      i += 1;
      let chunkStart = i;
      let braceDepth = 0;
      let inExpr = false;

      while (i < text.length) {
        const c = text[i];
        const n = text[i + 1];

        if (!inExpr) {
          if (c === '`' && !isEscaped(i)) {
            onHit({ start: chunkStart, value: text.slice(chunkStart, i) });
            i += 1;
            break;
          }

          if (c === '$' && n === '{' && !isEscaped(i)) {
            onHit({ start: chunkStart, value: text.slice(chunkStart, i) });
            inExpr = true;
            braceDepth = 1;
            i += 2;
            continue;
          }

          i += 1;
          continue;
        }

        if (c === '{') {
          braceDepth += 1;
          i += 1;
          continue;
        }

        if (c === '}') {
          braceDepth -= 1;
          i += 1;
          if (braceDepth <= 0) {
            inExpr = false;
            chunkStart = i;
          }
          continue;
        }

        i += 1;
      }

      continue;
    }

    i += 1;
  }
}

function failGeneratedOutput(filePath, reason, index, fullText) {
  const lc = toLineColumn(fullText, index);
  const snip = fullText.slice(Math.max(0, index - 40), Math.min(fullText.length, index + 40));

  console.error(
    [
      reason,
      'file=' + filePath,
      'line=' + lc.line,
      'column=' + lc.column,
      'snippet=' + JSON.stringify(snip),
    ].join(' '),
  );
  process.exit(1);
}

function assertGeneratedOutputEncoding(output, filePath) {
  for (const marker of OUTPUT_POLLUTION_MARKERS) {
    const idx = output.indexOf(marker);
    if (idx !== -1) {
      const reason = marker === '[QUESTION_PLACEHOLDER]'
        ? '[BUILD_ENCODING][BAD_PLACEHOLDER]'
        : '[BUILD_ENCODING][BAD_MARKER]';
      failGeneratedOutput(filePath, reason, idx, output);
    }
  }

  scanJsStringLiterals(output, (lit) => {
    const questionMatch = lit.value.match(BAD_QUESTION_MARK_RE);
    if (!questionMatch) return;

    const hitIdxInValue = lit.value.indexOf(questionMatch[0]);
    const hitIdx = lit.start + hitIdxInValue;
    failGeneratedOutput(filePath, '[BUILD_ENCODING][BAD_QUESTION_MARKS]', hitIdx, output);
  });
}

function escapeNonAsciiForJsSource(text) {
  let output = '';

  for (const char of text) {
    const codePoint = char.codePointAt(0);

    if (
      codePoint === 0x09
      || codePoint === 0x0a
      || codePoint === 0x0d
      || (codePoint >= 0x20 && codePoint <= 0x7e)
    ) {
      output += char;
      continue;
    }

    if (codePoint <= 0xffff) {
      output += '\\u' + codePoint.toString(16).padStart(4, '0');
    } else {
      output += '\\u{' + codePoint.toString(16) + '}';
    }
  }

  return output;
}

function assembleUserscript() {
  const config = loadBuildConfig();
  const allParts = config.parts || [];
  const marker = config.uploadInsertMarker || '/*__UPLOAD_MODULES__*/';
  const buildTime = getBuildTimeString();

  if (!allParts.length) {
    throw new Error('.build-order.json is missing "parts" array');
  }

  const mainText = readUtf8File(ENTRY_FILE);
  assertNoMojibake(mainText, 'core/main.js');

  const { header, body: mainBody } = extractHeader(mainText);

  if (!mainBody.includes(marker)) {
    throw new Error(
      'core/main.js is missing upload insert marker ' + marker + '. '
      + 'Check that the upload module part has a matching InsertModule block.',
    );
  }

  const bodyParts = allParts.map((partName) => {
    if (partName === 'core/main.js') {
      return mainBody.replace(marker, '\n');
    }

    const partText = readPart(partName);
    assertNoMojibake(partText, partName);
    return partText;
  });

  const body = bodyParts.join('');
  assertNoBadControlChars(body, 'assembled-source-body');
  assertNoMojibake(body, 'assembled-source-body');

  const runtimeBuildBanner = [
    "try {",
    `  console.log('[TOOLBOX][BUILD] generatedAt=${buildTime}');`,
    "} catch (e) {}",
    "",
  ].join('\n');

  const bundled = '(function () {\n  \'use strict\';\n\n' + runtimeBuildBanner + body + '})();';
  const bundledSanitized = bundled.replace(/\uFEFF/g, '');
  assertNoBadControlChars(bundledSanitized, 'bundled-sanitized');

  const asciiBundled = escapeNonAsciiForJsSource(bundledSanitized);

  return [header, buildGeneratedNotice(buildTime), asciiBundled, ''].join('\n\n');
}

function checkJavaScriptSyntax(filePath) {
  const result = spawnSync(process.execPath, ['--check', filePath], {
    encoding: 'utf8',
  });

  if (result.status !== 0) {
    const output = [
      result.stdout || '',
      result.stderr || '',
    ].join('\n').trim();

    throw new Error(
      'Generated userscript syntax check failed: ' + filePath + '\n' + output,
    );
  }
}

function writeOutput() {
  fs.mkdirSync(DIST_DIR, { recursive: true });

  const output = assembleUserscript();
  assertNoMojibake(output, 'generated-userscript');
  assertGeneratedOutputEncoding(output, OUT_FILE);

  fs.writeFileSync(OUT_FILE, output, 'utf8');
  checkJavaScriptSyntax(OUT_FILE);

  fs.writeFileSync(REPO_ROOT_CLIENT, output, 'utf8');
  checkJavaScriptSyntax(REPO_ROOT_CLIENT);

  console.log('[BUILD][OK] Wrote ' + OUT_FILE);
  console.log('[BUILD][OK] Synced ' + REPO_ROOT_CLIENT);
  console.log('[BUILD][OK] JS body escaped to ASCII-safe unicode literals');
  console.log('[BUILD][OK] Generated output encoding validation passed');
}

function watch() {
  writeOutput();

  console.log('Watching ' + SRC_DIR + ' ...');

  fs.watch(SRC_DIR, { recursive: true }, () => {
    try {
      writeOutput();
    } catch (err) {
      const message = err && err.stack ? err.stack : String(err);
      console.error('[BUILD][FAILED]\n' + message);
    }
  });
}

if (process.argv.includes('--watch')) {
  watch();
} else {
  writeOutput();
}
