import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT_DIR = path.dirname(fileURLToPath(import.meta.url));
const SRC_DIR = path.join(ROOT_DIR, 'tampermonkey-userscript-src');
const ENTRY_FILE = path.join(SRC_DIR, 'core', 'main.js');
const DIST_DIR = path.join(ROOT_DIR, 'dist');
const OUT_FILE = path.join(DIST_DIR, 'client.user.js');
const REPO_ROOT_CLIENT = path.join(ROOT_DIR, '..', 'client.user.js');
const ORDER_FILE = path.join(SRC_DIR, '.build-order.json');

function loadBuildConfig() {
  if (!fs.existsSync(ORDER_FILE)) {
    throw new Error('.build-order.json not found at ' + ORDER_FILE);
  }
  return JSON.parse(fs.readFileSync(ORDER_FILE, 'utf8'));
}

function pad2(n) {
  return String(n).padStart(2, '0');
}

function buildGeneratedNotice() {
  const now = new Date();
  const buildTime = [
    now.getFullYear(),
    pad2(now.getMonth() + 1),
    pad2(now.getDate()),
  ].join('-') + ' ' + pad2(now.getHours()) + ':' + pad2(now.getMinutes()) + ':' + pad2(now.getSeconds());

  return [
    '// =============================================================================',
    '// GENERATED FILE - DO NOT EDIT DIRECTLY',
    '// =============================================================================',
    '// This file is generated by:',
    '// chatgpt-toolbox/build.userjs.mjs',
    '//',
    '// Source files are in:',
    '// chatgpt-toolbox/tampermonkey-userscript-src/',
    '//',
    '// To modify behavior, edit source files first, then run:',
    '// npm run build',
    '//',
    '// Generated at: ' + buildTime,
    '// =============================================================================',
  ].join('\n');
}

function extractHeader(mainText) {
  const match = mainText.match(/^\/\/ ==UserScript==[\s\S]*?\/\/ ==\/UserScript==\r?\n/);
  if (!match) {
    throw new Error('Userscript header not found in ' + ENTRY_FILE);
  }
  return {
    header: match[0].trimEnd(),
    body: mainText.slice(match[0].length),
  };
}

function readPart(name) {
  const filePath = path.join(SRC_DIR, name);
  if (!fs.existsSync(filePath)) {
    throw new Error('Missing source part: ' + filePath);
  }
  return fs.readFileSync(filePath, 'utf8');
}

function assembleUserscript() {
  const config = loadBuildConfig();
  const allParts = config.parts || [];
  const marker = config.uploadInsertMarker || '/*__UPLOAD_MODULES__*/';

  if (!allParts.length) {
    throw new Error('.build-order.json is missing "parts" array');
  }

  const mainText = fs.readFileSync(ENTRY_FILE, 'utf8');
  const { header, body: mainBody } = extractHeader(mainText);

  // Build body from all non-entry parts
  const nonEntryParts = allParts.filter(function(p) { return p !== 'core/main.js'; });
  const bodyParts = nonEntryParts.map(function(p) { return readPart(p); });

  // Expand the upload marker in main.js body
  if (!mainBody.includes(marker)) {
    throw new Error(
      'core/main.js is missing upload insert marker ' + marker + '. ' +
      'Check that the upload module part has a matching InsertModule block.'
    );
  }
  bodyParts.push(mainBody.replace(marker, '\n'));

  const body = bodyParts.join('');
  const bundled = '(function () {\n  \'use strict\';\n\n' + body + '})();';
  return [header, buildGeneratedNotice(), bundled, ''].join('\n\n');
}

function writeOutput() {
  fs.mkdirSync(DIST_DIR, { recursive: true });
  const output = assembleUserscript();
  fs.writeFileSync(OUT_FILE, output, 'utf8');
  fs.writeFileSync(REPO_ROOT_CLIENT, output, 'utf8');
  console.log('Wrote ' + OUT_FILE);
  console.log('Synced ' + REPO_ROOT_CLIENT);
}

function watch() {
  writeOutput();
  console.log('Watching ' + SRC_DIR + ' ...');
  fs.watch(SRC_DIR, { recursive: true }, function() {
    try {
      writeOutput();
    } catch (err) {
      console.error(err);
    }
  });
}

if (process.argv.includes('--watch')) {
  watch();
} else {
  writeOutput();
}
