# Import browser-downloaded refactor_runtime_verification_20260604_runtime.txt
# into exports/for_chatgpt/, split into 7 logs, then validate.
#
# Usage (after oneshot paste in Chrome/Edge DevTools):
#   powershell -File tools/import_runtime_verification_download.ps1
#   powershell -File tools/import_runtime_verification_download.ps1 -SourcePath "C:\Users\you\Downloads\refactor_runtime_verification_20260604_runtime.txt"

param(
    [string]$SourcePath = '',
    [string]$OutDir = (Join-Path (Split-Path -Parent $PSScriptRoot) 'exports\for_chatgpt')
)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$dest = Join-Path $OutDir 'refactor_runtime_verification_20260604_runtime.txt'

if (-not $SourcePath) {
    $dl = Join-Path $env:USERPROFILE 'Downloads'
    if (Test-Path $dl) {
        $candidates = Get-ChildItem -Path $dl -Filter 'refactor_runtime_verification_20260604*.txt' -File -ErrorAction SilentlyContinue |
            Sort-Object LastWriteTime -Descending
        if ($candidates) {
            $SourcePath = $candidates[0].FullName
            Write-Host "[IMPORT] auto-picked latest download: $SourcePath"
        }
    }
}

if (-not $SourcePath -or -not (Test-Path $SourcePath)) {
    Write-Host '[IMPORT] No source file.'
    Write-Host '  1. Chrome/Edge on https://chatgpt.com (logged in, Tampermonkey ONLY dist/client.user.js)'
    Write-Host '  2. DevTools Console: paste exports/for_chatgpt/refactor_runtime_oneshot_verify_download.js'
    Write-Host '  3. Save browser download, then re-run with -SourcePath <full path>'
    exit 1
}

$raw = Get-Content -Path $SourcePath -Raw -Encoding UTF8
if ($raw -match 'PENDING_USER_RUN|"status"\s*:\s*"PENDING') {
    Write-Error 'Source is still a PENDING template — run oneshot in real browser first'
}
if ($raw -notmatch '"summary"\s*:|Generated by refactor_runtime_oneshot_verify_download\.js|REFACTOR RUNTIME VERIFY DONE') {
    Write-Error 'Source does not look like oneshot export (missing summary / oneshot marker)'
}

New-Item -ItemType Directory -Force -Path $OutDir | Out-Null
Copy-Item -Path $SourcePath -Destination $dest -Force
Write-Host "[IMPORT] copied -> $dest ($((Get-Item $dest).Length) bytes)"

Push-Location $root
try {
    node tools/split-refactor-runtime-export.mjs $dest
    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
    & (Join-Path $PSScriptRoot 'validate_runtime_verification_logs.ps1')
    exit $LASTEXITCODE
}
finally {
    Pop-Location
}
