# Validates exports/for_chatgpt/*_20260604*.txt runtime verification artifacts.
# Exit 0 = all present and pattern checks pass; exit 1 = missing or failed checks.

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$dir = Join-Path $root 'exports\for_chatgpt'

$files = @{
    'refactor_runtime_verification_20260604_runtime.txt' = @(
        '"summary"\s*:',
        '"report"\s*:',
        'Generated by refactor_runtime_oneshot_verify_download\.js|REFACTOR RUNTIME VERIFY DONE'
    )
    'send_message_button_log_20260604.txt' = @(
        '\[SEND_PIPELINE\]\[ENTRY\]',
        '\[SEND_PIPELINE\]\[FINISH\]'
    )
    'send_copy_hotkey_button_log_20260604.txt' = @(
        '\[UPLOAD\]\[SKIP_LOCAL_QUEUE_FOR_SEND_COPY_HOTKEY\]',
        'action=',
        'source=',
        'activeFiles=',
        'runId=',
        'rule=send-current-composer-only'
    )
    'closed_loop_success_log_20260604.txt' = @(
        '\[CLOSED_LOOP\]\[DISPATCH_RESULT\].*ok=1'
    )
    'closed_loop_failure_log_20260604.txt' = @(
        '\[CLOSED_LOOP\]\[DISPATCH_RESULT\].*ok=0|\[CLOSED_LOOP\]\[DISPATCH_FAILED\]'
    )
    'upload_button_log_20260604.txt' = @(
        '\[UPLOAD\]|\[BRIDGE\]\[UPLOAD\]|UPLOAD'
    )
    'runtime_edge_cases_log_20260604.txt' = @(
        'empty|duplicate|runId|reply|edge|blocked|empty_text',
        '.'
    )
}

$forbiddenUpload = @(
    'candidate=1',
    '\[UPLOAD_RUNNER\]\[START\] candidate=1',
    '\[UPLOAD_SEND_FLOW\]\[START\] candidate=1'
)

$fail = 0
Write-Host "[VALIDATE] dir=$dir"

foreach ($name in $files.Keys) {
    $path = Join-Path $dir $name
    if (-not (Test-Path $path)) {
        Write-Host "[MISSING] $name"
        $fail = 1
        continue
    }
    $text = Get-Content -Path $path -Raw -Encoding UTF8
    if ($text -match 'PENDING_USER_RUN|"status"\s*:\s*"PENDING') {
        Write-Host "[TEMPLATE_ONLY] $name — replace with real browser export"
        $fail = 1
        continue
    }
    if ([string]::IsNullOrWhiteSpace($text)) {
        Write-Host "[EMPTY] $name"
        $fail = 1
        continue
    }
    foreach ($pat in $files[$name]) {
        if ($text -notmatch $pat) {
            Write-Host "[PATTERN_FAIL] $name pattern=$pat"
            $fail = 1
        }
    }
    if ($name -eq 'upload_button_log_20260604.txt') {
        foreach ($bad in $forbiddenUpload) {
            if ($text -match $bad) {
                Write-Host "[FORBIDDEN] $name matched $bad"
                $fail = 1
            }
        }
    }
    if ($name -eq 'send_message_button_log_20260604.txt') {
        if ($text -match '\[UPLOAD\]\[START\]|\[UPLOAD\]\[QUEUE_START\]') {
            Write-Host "[FORBIDDEN] $name must not start upload queue"
            $fail = 1
        }
    }
    Write-Host "[OK] $name ($((Get-Item $path).Length) bytes)"
}

if ($fail -eq 0) {
    Write-Host '[VALIDATE] ALL RUNTIME LOGS READY — safe to include in next export zip'
    exit 0
}
Write-Host '[VALIDATE] INCOMPLETE — browser verification still required'
exit 1
